# The joint state controller handles publishing transforms for any moving joints
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


# Position Controllers ---------------------------------------
steering0_position_controller:
  type: effort_controllers/JointPositionController
  joint: steering0
  pid: {p: 100, i: 0.1, d: 10.0}
wheel0_position_controller:
  type: effort_controllers/JointPositionController
  joint: wheel0
  pid: {p: 100, i: 0.1, d: 10.0}

steering1_position_controller:
  type: effort_controllers/JointPositionController
  joint: steering1
  pid: {p: 100, i: 0.1, d: 10.0}
wheel1_position_controller:
  type: effort_controllers/JointPositionController
  joint: wheel1
  pid: {p: 100, i: 0.1, d: 10.0}

steering2_position_controller:
  type: effort_controllers/JointPositionController
  joint: steering2
  pid: {p: 100, i: 0.1, d: 10.0}
wheel2_position_controller:
  type: effort_controllers/JointPositionController
  joint: wheel2
  pid: {p: 100, i: 0.1, d: 10.0}

steering3_position_controller:
  type: effort_controllers/JointPositionController
  joint: steering3
  pid: {p: 100, i: 0.1, d: 10.0}
wheel3_position_controller:
  type: effort_controllers/JointPositionController
  joint: wheel3
  pid: {p: 100, i: 0.1, d: 10.0}

